[[redirects]]
  from = "/api/coinone/*"
  to = "https://api.coinone.co.kr/public/v2/:splat"
  status = 200
  force = true
  queryString = "retain"

[[redirects]]
  from = "/api/mexc/*"
  to = "https://api.mexc.com/api/v3/:splat"
  status = 200
  force = true
  queryString = "retain"

[[redirects]]
  from = "/api/upbit/*"
  to = "https://api.upbit.com/v1/:splat"
  status = 200
  force = true
  queryString = "retain"